### PR TITLE
Restore 3.0 to CI, bump gemspec

### PR DESCRIPTION
**Pull request by mjankowski**
Context: https://github.com/standardrb/standard-performance/pull/26#issuecomment-2171548753

Prep for possible aligned release of standard/-rails/-performance

### CODE REVIEW

**Comment by mjankowski** [comment]
Added commit to also bump `TargetRubyVersion` (RE: https://github.com/standardrb/standard-performance/pull/26#issuecomment-2171671971)

**Comment by mjankowski** [comment]
Another possible update here ... looks like the `Standard::Base::Plugin` class has a method that does yaml merging for backwards support of many ruby versions, with each version inheriting from the next highest one and disabling the cops added in that higher version. So probably...

- If we are doing a hard drop of support for pre-3.0 ... can we remove all the 1.x and 2.x yaml files and conditional cases in that plugin file?
- We probably need a 3.3 yml added, and to update 3.2 yml (if any relevant drops exist, I'm not sure yet)

**Comment by searls** [comment]
@mjankowski no, those are all there intentionally. Standard is designed to allow users to target ancient Rubies. If you run Standard under a supported-by-rubocop Ruby against a 1.8.7 codebase by setting TargetRubyVersion, it'll still be able to lint/format without breaking 1.8.7 compatibility

**Comment by mjankowski** [comment]
Oh right - disconnect between runtime support and linting target support. Got it.

Pushed another commit here which adds 3.3 yml and adjusts 3.2 in what I think is correct mirroring other files. As far as I can see there are not any cops which need 3.3 as minimum.

**Pull request merged**
