### PR TITLE
fix `emabled` typo in Style/SafeNavigationChainLength

### LINKED ISSUE #662: Typo `emabled` in recent release for Style/SafeNavigationChainLength
```
Style/SafeNavigationChainLength:
  Emabled: false
```

should be `enabled`

### PR DESCRIPTION
**Pull request by jeffbax**
Fixes a typo in the enabled flag in the 1.42.0 release

closes #662

### CODE REVIEW

**Comment by mjankowski** [comment]
Worth doing a `1.42.1` release for this?

**Comment by jeffbax** [comment]
> Worth doing a `1.42.1` release for this?

I think it would be worth it, it is kind of annoying and probably a lot of people who haven't upgraded to the typo yet.

**Comment by mjankowski** [comment]
Related - I wonder if we could have caught that issue. I know rubocop has a pretty robust linter/config-validator ... presumably there'd be some code-level "load out rules and verify no warnings present" sort of check we could add to suite...

**Comment by pboling** [comment]
This generates hundreds of lines of noise on my projects, which leads me to consider it a fully broken release.  Noise is dangerous when I need to see real issues in my build.

**Comment by searls** [comment]
Apologies for the delay in cutting a release. At least two gem owners (including myself) are currently traveling without access to a computer. Trying to get ahold of someone who can cut one

**Comment by camilopayan** [comment]
v1.42.1 is out! Sorry for missing this PR

**Pull request merged**
